name = "ghostb_cTab"
mainprefix = "z"
prefix = "ctab_ghostb"
author = "cTab Authors, see https://github.com/jetelain/cTab"

[files]
include = [
    "mod.cpp",
    "ctab_ico.paa"
]

[lint.sqf]
enabled = true # Default: true
exclude = [
    "a3/3DEN/UI/macroexecs.inc",
    "macroexecs.inc",
    "a3/ui_f/hpp/defineResincl.inc",
    "a3/ui_f/hpp/defineDIKCodes.inc",
    "a3/ui_f/hpp/defineCommonGrids.inc",
    "a3/ui_f/hpp/defineCommonColors.inc",
]

[Rapify]
exclude = [
    "macroexecs.inc"
]

[asc]
enabled = true # Default: false
exclude = [
]