name = "ghostb_cTab IRL"
prefix = "ctab_irl_ghostb"
author = "cTab Authors, see https://github.com/jetelain/cTab"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3
files = [
    "mod.cpp",
    "*.dll",
    "icon_ctab_irl.paa"
]